const { Quiz } = require('../models');

quizData =[
    {
        q1: 'In the lesson plan, what does "CRS" stand for?',
        q1a1: 'Credited Roster System',
        q1a2: 'Classroom Session',
        q1a3: 'Car Reevaluation Standard',
        q1a4: 'Classic Rally Sport',
        q1correct_a: 2,
        q2: 'How can I access the next lesson?',
        q2a1: 'Just click on the next lesson',
        q2a2: 'Ask for the access',
        q2a3: 'get 4 out of 5 questions right on the previous lesson quiz',
        q2a4: 'bribery',
        q2correct_a: 3,
        q3: 'I just want to work on cars, do I have to do Classroom Sessions too?',
        q3a1: 'Yes, all students who wish to work on a real car must be learning the classroom sessions first.',
        q3a2: 'yeah, but I don\'t have to pay attention',
        q3a3: 'no, if I just want to work on cars, I can just show up on LAB days',
        q3a4: 'if I\'ve already done some work on my own car, I don\'t have to attend classroom sessions',
        q3correct_a: 1,
        q4: 'Why do I need to learn the tool\'s names if I know how to use them',
        q4a1: 'if I can demonstrate how to use all of the tools, I can be omitted from having to know their names',
        q4a2: 'you don\'t NEED to, it would just be nice',
        q4a3: 'to impress my friends',
        q4a4: 'You should know how to reference the tools by name for communicating in this class and when working in a shop with others.',
        q4correct_a: 4,
        q5: 'Which is NOT a reason safety is important',
        q5a1: 'if protects you from temporary or permanent bodily harm',
        q5a2: 'it protects the car from damage',
        q5a3: 'if protects the tools from damage',
        q5a4: 'all of these are reasons why safety IS important',
        q5correct_a: 4,
        reward_code: 'VV-_W1L1_-VV',
        lesson_id: 1
    },
    {
        q1: 'What is a fastener?',
        q1a1: 'the part of a car used for acceleration',
        q1a2: 'a person who ties things down for transport',
        q1a3: 'a device that makes things happen faster',
        q1a4: 'a generic term for components that hold 2 or more parts of a machine together.',
        q1correct_a: 4,
        q2: 'Which is NOT a property to describe a bolt specification?',
        q2a1: 'weight',
        q2a2: 'thread pitch',
        q2a3: 'threads per inch',
        q2a4: 'length',
        q2correct_a: 1,
        q3: 'What is a torquing sequence?',
        q3a1: 'a series of stretches to do before tightening down a fastener',
        q3a2: 'the order of bolts around a part to be bolted on in clockwise direction',
        q3a3: 'the order in which multiple fasteners should be tightened',
        q3a4: 'the order in which parts should be installed',
        q3correct_a: 3,
        q4: 'In relation to automotive fasteners, why might someone use a "washer"?',
        q4a1: 'to make tightening down a fastener easier',
        q4a2: 'to spread a fastener\'s clamping load out to prevent surface damage and tear out',
        q4a3: 'to clean their clothes',
        q4a4: 'every nut and bolt should be accompanied by a washer for automotive use',
        q4correct_a: 2,
        q5: 'What is a drawback to metal rivets?',
        q5a1: 'they are very heavy',
        q5a2: 'they are expensive',
        q5a3: 'the require special tools to install and remove',
        q5a4: 'they are bulky',
        q5correct_a: 3,
        reward_code: 'VV-_W1L2_-VV',
        lesson_id: 2
    },
    {
        q1: 'What is "driving" a fastener?',
        q1a1: 'setting a fastener in place using a thread locking compound',
        q1a2: 'putting it in your car to transport it to another place',
        q1a3: 'using a tool to rotate a threaded fastener in place',
        q1a4: 'drilling a hole into a fastener head for a safety pin or wire',
        q1correct_a: 3,
        q2: 'Which is not a fastener drive type we covered?',
        q2a1: 'circle',
        q2a2: 'square',
        q2a3: 'hex',
        q2a4: 'Torx',
        q2correct_a: 1,
        q3: 'Which drive type is the most commonly used in the auto industry?',
        q3a1: 'hex',
        q3a2: 'Philips',
        q3a3: 'square',
        q3a4: 'slotted',
        q3correct_a: 1,
        q4: 'If an automaker does not want users working on the car, they might use a _______ fastener.',
        q4a1: 'robinson (male)',
        q4a2: 'Torx',
        q4a3: 'slotted',
        q4a4: 'hex',
        q4correct_a: 2,
        q5: 'Philips drive screws are popular for their ability to "self-center" but have a major downside. what is it?',
        q5a1: 'they require more effort to turn',
        q5a2: 'they only come in one size',
        q5a3: 'they only self center when being turned clockwise',
        q5a4: 'they are easy to strip by "camming out"',
        q5correct_a: 4,
        reward_code: 'VV-_W1L3_-VV',
        lesson_id: 3
    },
    {
        q1: 'What is a wrench?',
        q1a1: 'a tool used for lifting a vehicle',
        q1a2: 'a tool used to drive threaded fasteners with high torque using leverage',
        q1a3: 'a tool used to pry apart 2 parts of a car',
        q1a4: 'a tool the can be used as a hammer',
        q1correct_a: 2,
        q2: 'Another name for an open ended wrench is a:',
        q2a1: 'pipe wrench',
        q2a2: 'monkey wrench',
        q2a3: 'crescent wrench',
        q2a4: 'open sesame wrench',
        q2correct_a: 3,
        q3: 'Where might a box ended wrench be favorable to an open ended wrench?',
        q3a1: 'if the open ended wrench keeps slipping off of the fastener while attempting to turn',
        q3a2: 'if there is no way to access the fastener from the side and only from the top',
        q3a3: 'if there is not a lot of room to "swing" the wrench',
        q3a4: 'if the open ended wrench is engaging the fastener',
        q3correct_a: 1,
        q4: 'What makes a combination wrench so popular and versatile?',
        q4a1: 'It can be used to drive male AND female threaded fasteners',
        q4a2: 'It is a wrench AND a bottle opener',
        q4a3: 'It contains both an open end AND a box end',
        q4a4: 'It is cheaper to manufacture than other types of wrenches.',
        q4correct_a: 3,
        q5: 'Why is it good to understand the subtle differences of the basic wrench types?',
        q5a1: 'To have had a chance to try them all so you can buy only the kind you prefer to work with.',
        q5a2: 'To know which types of wrenches someone else is using so you can impress them by talking about their wrench.',
        q5a3: 'Understanding which type of wrench best suits the situation goes a long way to make the experience of working on cars go smoothly.',
        q5a4: 'Its trivial information, but it is just interesting.',
        q5correct_a: 3,
        reward_code: 'VV-_W1L4_-VV',
        lesson_id: 4
    },
    {
        q1: 'Why is a NOT an advantage of a socket wrench?',
        q1a1: 'there are a vast assortment of sockets and accessories that increase its functionality',
        q1a2: 'socket wrenches function as both a box ended wrench and as open ended wrench',
        q1a3: 'the ratcheting action allows for a very short tool "swing"',
        q1a4: 'they are available in many sizes',
        q1correct_a: 2,
        q2: 'What part of an adjustable wrench adjusts when you turn the worm screw?',
        q2a1: 'the distance between the jaws',
        q2a2: 'the length of the handle',
        q2a3: 'the number of engaging faces',
        q2a4: 'the drive type (Torx, Philips, Slotted, etc.)',
        q2correct_a: 1,
        q3: 'When would you use a flare wrench over an open ended wrench?',
        q3a1: 'when working on hydraulic lines with soft aluminum fasteners',
        q3a2: 'when you need to drive a square drive type fastener',
        q3a3: 'when your open ended wrench keeps slipping off of the fastener',
        q3a4: 'when you need a ratcheting action to shorten the tool swing',
        q3correct_a: 1,
        q4: 'Why would one use a torque wrench?',
        q4a1: 'To avoid stripping fasteners',
        q4a2: 'To prevent fasteners from backing out',
        q4a3: 'To prevent parts from warping or deforming',
        q4a4: 'For all of the above reasons',
        q4correct_a: 4,
        q5: 'What does 20 foot pounds of torque represent?',
        q5a1: 'The force of someone pounding their foot into the wrench twenty times',
        q5a2: 'Twenty pounds of force applied 10 feet away from the center of rotation.',
        q5a3: 'Twenty pounds of force applied 1 foot away from the center of rotation',
        q5a4: 'All of these equally represent 20 foot pounds of torque.',
        q5correct_a: 3,
        reward_code: 'VV-_W1L5_-VV',
        lesson_id: 5
    },
    {
        q1: 'Can you use a socket wrench to drive hex fasteners without sockets?',
        q1a1: 'socket wrenches can drive hex bolts without sockets. They sockets just increase the versatility.',
        q1a2: 'no, the wrench requires sockets and batteries to drive hex fasteners',
        q1a3: 'yes, using other attachments, you can',
        q1a4: 'no, the sockets are the key reason socket wrenches are so popular',
        q1correct_a: 4,
        q2: 'Which is NOT an advantage of a 6 point socket over a 12 point socket',
        q2a1: 'a 6 point socket is stronger',
        q2a2: 'a 6 point socket is less likely to round out a rusty fastener',
        q2a3: 'a 6 point socket is easier to engage the fastener with',
        q2a4: 'a 6 point fastener makes more metal-to-metal contact',
        q2correct_a: 3,
        q3: 'Which is NOT a distinguishing socket feature',
        q3a1: 'shallow',
        q3a2: 'double sided',
        q3a3: 'deep',
        q3a4: 'thin wall',
        q3correct_a: 2,
        q4: 'Thin walled sockets can be a life saver, what is their disadvantage?',
        q4a1: 'the thin walls give easy access radially',
        q4a2: 'the thin walls are easier to crack under stress',
        q4a3: 'the thin walls make the tool too light and unbalanced',
        q4a4: 'the thin walls make the tool harder to engage the fastener',
        q4correct_a: 2,
        q5: 'What does a black color on a socket signify?',
        q5a1: 'the socket is rated for use on an impact wrench',
        q5a2: 'the socket must be oiled before use',
        q5a3: 'the socket functions as both a 12 and 6 point socket',
        q5a4: 'the socket is a deep well socket',
        q5correct_a: 1,
        reward_code: 'VV-_W1L6_-VV',
        lesson_id: 6
    },
     {
        q1: 'What would a ”drive adapter“ let you do?',
        q1a1: 'turn a front or rear wheel drive car into all wheel drive',
        q1a2: 'move the steering wheel to the other side for different global regions',
        q1a3: 'allow sockets of a different drive size to be installed onto an otherwise non-compatible socket wrench',
        q1a4: 'shift manually with an automatic transmission',
        q1correct_a: 3,
        q2: 'Which is NOT true about socket extensions',
        q2a1: 'they are a straight metal shaft with a male square drive on one side and a female square drive on the other',
        q2a2: 'they help in driving sockets in areas that are too cramped to put the socket wrench',
        q2a3: 'they come in many sizes and lengths',
        q2a4: 'all of these are true about extensions',
        q2correct_a: 4,
        q3: 'What is a swivel?',
        q3a1: 'a component between a socket wrench and socket, that allows the socket to be driven at an angle',
        q3a2: 'a pivot point to rest your arm on while pulling a wrench so that you don\'t get tired',
        q3a3: 'a chair mechanics sit on under a lifted car to give access in 360° without having to stand',
        q3a4: 'a clamp that will hold a car part in place for you while you bolt it down. It can be repositioned and “swivelled” as needed.',
        q3correct_a: 1,
        q4: 'What is the problem with using a swivel?',
        q4a1: 'swivels make working on a car too easy',
        q4a2: 'swivels cannot transmit constant torque, and should NOT be in conjunction used with a torque wrench',
        q4a3: 'swivels are not strong enough to drive most fasteners',
        q4a4: 'swivels reduce the swing angle of your tool',
        q4correct_a: 2,
        q5: 'Which is the best socket accessory or combo of accessories would you use to attach your 1/4" drive 8mm socket to your 3/8" torque wrench?',
        q5a1: 'a 3/8" to 1/2" “step up” drive adapter to a 1/2" to 1/4" “step down” drive adapter',
        q5a2: 'an 3/8" drive 8 inch extension and a 3/8" drive swivel with a 3/8" to 1/4" “step down” drive adapter.',
        q5a3: 'a 1/4" to 3/8" “step up” drive adapter',
        q5a4: 'a 3/8" to 1/4" “step down” drive adapter',
        q5correct_a: 4,
        reward_code: 'VV-_W1L7_-VV',
        lesson_id: 7
    },
    {
        q1: 'What are pliers?',
        q1a1: 'a tool used to drive threaded fasteners with high torque using leverage',
        q1a2: 'a tool used for layering sheets on top of one another (1 ply, 2 ply, etc.)',
        q1a3: 'a tool used to pry 2 things apart',
        q1a4: 'tools with 2 handles that are squeezed together to clamp a pair of jaws',
        q1correct_a: 4,
        q2: 'What is one difference between square nose pliers and needle nose pliers?',
        q2a1: 'square nose pliers are always longer than needle nose pliers',
        q2a2: 'square nose pliers have bulkier jaws than needle nose pliers',
        q2a3: 'square nose pliers are easier to squeeze together than needle nose pliers',
        q2a4: 'needle nose pliers are reverse operation, meaning they spread open when closing the handles',
        q2correct_a: 2,
        q3: 'What is another name for locking pliers?',
        q3a1: 'Vice Grips',
        q3a2: 'Channel Lock Pliers',
        q3a3: 'Tin Snips',
        q3a4: 'Freeze Grip Pliers',
        q3correct_a: 1,
        q4: 'Which of the following is a fact about snap ring pliers?',
        q4a1: 'instead of jaws they have hardened and tapered blades for cutting',
        q4a2: 'they always have a locking feature',
        q4a3: 'there are 2 types. Internal, and Externals',
        q4a4: 'they are older versions of needle nose pliers',
        q4correct_a: 3,
        q5: 'Which type of plier would be used to cut sheet metal?',
        q5a1: 'Snips',
        q5a2: 'Snap Ring',
        q5a3: 'Needle Nose',
        q5a4: 'Tin Snips',
        q5correct_a: 4,
        reward_code: 'VV-_W1L8_-VV',
        lesson_id: 8
    },
    {
        q1: 'What are some hazzards one could face if they choose to not use safety goggles?',
        q1a1: 'dirt can fall into the eyes',
        q1a2: 'sharp metal can fly into eyes after part failure',
        q1a3: 'chemicals and oils that cause blindness can enter the eyes',
        q1a4: 'all of these are the risks for not using safety goggles',
        q1correct_a: 4,
        q2: 'What reason do I say that you can choose to carefully work without wearing gloves?',
        q2a1: 'if they\'re making your hands sweaty',
        q2a2: 'if they are making the job more difficult to do',
        q2a3: 'if they are a bigger hazard than bare hands for fear of snagging on part of the car',
        q2a4: 'options b and c',
        q2correct_a: 4,
        q3: 'What is a sign you should be using hearing protection?',
        q3a1: 'if you hear ringing in your ears after working on a car',
        q3a2: 'it is too loud to cary a conversation while working on a car',
        q3a3: 'nothing about working on a car is loud enough to warrant hearing protection',
        q3a4: 'you should always wear hearing protection for any automotive service',
        q3correct_a: 1,
        q4: 'What tool(s) do you need to be qualified to work under a car?',
        q4a1: 'a jack',
        q4a2: 'a jack and a crawler',
        q4a3: 'a jack and a set of jack stands',
        q4a4: 'a torque wrench',
        q4correct_a: 3,
        q5: 'Which is NOT a reason to use jack stands while working under a car?',
        q5a1: 'A jack can fail and drop the car on you',
        q5a2: 'I\'m only going to be under the car for a few minutes to change a wheel',
        q5a3: 'This class is saying I have to',
        q5a4: 'A car falling off of a jack can disfigure or even kill you.',
        q5correct_a: 2,
        reward_code: 'VV-_W1L9_-VV',
        lesson_id: 9
    }, /*
     {
        q1: '',
        q1a1: '',
        q1a2: '',
        q1a3: '',
        q1a4: '',
        q1correct_a: 0,
        q2: '',
        q2a1: '',
        q2a2: '',
        q2a3: '',
        q2a4: '',
        q2correct_a: 0,
        q3: '',
        q3a1: '',
        q3a2: '',
        q3a3: '',
        q3a4: '',
        q3correct_a: 0,
        q4: '',
        q4a1: '',
        q4a2: '',
        q4a3: '',
        q4a4: '',
        q4correct_a: 0,
        q5: '',
        q5a1: '',
        q5a2: '',
        q5a3: '',
        q5a4: '',
        q5correct_a: 0,
        reward_code: 'VV-_W1L10_-VV',
        lesson_id: 10
    },
     {
        q1: '',
        q1a1: '',
        q1a2: '',
        q1a3: '',
        q1a4: '',
        q1correct_a: 0,
        q2: '',
        q2a1: '',
        q2a2: '',
        q2a3: '',
        q2a4: '',
        q2correct_a: 0,
        q3: '',
        q3a1: '',
        q3a2: '',
        q3a3: '',
        q3a4: '',
        q3correct_a: 0,
        q4: '',
        q4a1: '',
        q4a2: '',
        q4a3: '',
        q4a4: '',
        q4correct_a: 0,
        q5: '',
        q5a1: '',
        q5a2: '',
        q5a3: '',
        q5a4: '',
        q5correct_a: 0,
        reward_code: 'VV-_W1L11_-VV',
        lesson_id: 11
    },
     {
        q1: '',
        q1a1: '',
        q1a2: '',
        q1a3: '',
        q1a4: '',
        q1correct_a: 0,
        q2: '',
        q2a1: '',
        q2a2: '',
        q2a3: '',
        q2a4: '',
        q2correct_a: 0,
        q3: '',
        q3a1: '',
        q3a2: '',
        q3a3: '',
        q3a4: '',
        q3correct_a: 0,
        q4: '',
        q4a1: '',
        q4a2: '',
        q4a3: '',
        q4a4: '',
        q4correct_a: 0,
        q5: '',
        q5a1: '',
        q5a2: '',
        q5a3: '',
        q5a4: '',
        q5correct_a: 0,
        reward_code: 'VV-_W1L12_-VV',
        lesson_id: 12
    },
     {
        q1: '',
        q1a1: '',
        q1a2: '',
        q1a3: '',
        q1a4: '',
        q1correct_a: 0,
        q2: '',
        q2a1: '',
        q2a2: '',
        q2a3: '',
        q2a4: '',
        q2correct_a: 0,
        q3: '',
        q3a1: '',
        q3a2: '',
        q3a3: '',
        q3a4: '',
        q3correct_a: 0,
        q4: '',
        q4a1: '',
        q4a2: '',
        q4a3: '',
        q4a4: '',
        q4correct_a: 0,
        q5: '',
        q5a1: '',
        q5a2: '',
        q5a3: '',
        q5a4: '',
        q5correct_a: 0,
        reward_code: 'VV-_W1L13_-VV',
        lesson_id: 13
    }, */
];

const seedQuizzes = () => Quiz.bulkCreate(quizData);

module.exports = seedQuizzes;